### ISSUE TITLE
Missing /avatar in the url for gravatar icons

### ISSUE THREAD

**Issue by guillaumevincent** [pelican-plugins/avatar#11]
Empty icon is pointing to `https://www.gravatar.com/a8b97ff8bd7957988dfe975eb75e7f0d` instead of `https://www.gravatar.com/avatar/a8b97ff8bd7957988dfe975eb75e7f0d`

## How to reproduce the issue:

just add `AVATAR_USE_GRAVATAR = True` in the pelican.conf

**Comment by rlaboiss** [comment]
Thanks for your issue report. Fixed in release 1.0.2.
