### ISSUE TITLE
Cannot read configuration...

### ISSUE THREAD

**Issue by mpaglia0** [pelican-plugins/avatar#17]
I am trying to write my first plugin but cannot read configuration parameters from config file...
I have looked into many plugins and noticed a big part of them use settings.get('PARAMETER') in order to read the value of PARAMETER in the config file but I cannot obtain any value in this way.
If I write - for example:
`def initialize(pelican):
   sitename = pelican.settings.get('SITENAME')`
I always obtain the error: name 'sitename' is not defined.

Unfortunately I cannot find any documentation helping to write a new plugin. I am sorry.
I am also very new with Python but the plugin I am trying to write is simple and manu functions are already working :-)

Thank you for your kind help

**Comment by rlaboiss** [comment]
Have you considered asking for help directly to the upstream authors of Pelican? Please, see the instructions at 
https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst

**Comment by mpaglia0** [comment]
@rlaboiss thank you indeed and please apologize for my stupid request! As soon as I noted it was addressed in the wrong place I cancelled it...
Sorry.
